name: crud_table_example
description: Demonstrates how to use the crud_table plugin.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  crud_table:
    path: ../

  freezed_annotation: ^2.0.3

  cupertino_icons: ^1.0.5

  google_maps_flutter: ^2.6.1
  
  google_maps_flutter_web: ^0.5.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.1.11
  freezed: ^2.0.3+1
  json_serializable: ^6.2.0

flutter:

  uses-material-design: true

