name: crud_table
description: A package for creating CRUD Admin tables.
version: 0.3.0
homepage:

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  
  freezed_annotation: ^0.14.2

  intl: ^0.17.0

  data_table_2: ^2.0.3

  date_time_picker: ^2.0.0

  google_maps_flutter: ^2.0.6
  google_maps_flutter_web: ^0.3.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.0.4
  freezed: ^0.14.2
  lint: ^1.5.3

flutter:
