name: crud_table
description: A package for creating CRUD Admin tables.
version: 0.6.0
homepage:

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=3.0.1"

dependencies:
  flutter:
    sdk: flutter
  
  freezed_annotation: ^2.0.3

  intl: ^0.17.0

  data_table_2: ^2.3.0

  date_time_picker: ^2.1.0

  google_maps_flutter: ^2.6.1
  google_maps_flutter_web: ^0.5.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.1.11
  freezed: ^2.0.3+1
  lint: ^1.8.2

flutter:
